"""v1.0

Revision ID: 4f6e92cae06c
Revises: 
Create Date: 2017-07-30 21:40:23.973645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6e92cae06c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_searches_search_name'), 'searches', ['search_name'], unique=False)
    op.create_table('novels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(length=64), nullable=True),
    sa.Column('book_url', sa.String(), nullable=True),
    sa.Column('book_img', sa.String(), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('style', sa.String(length=64), nullable=True),
    sa.Column('last_update', sa.String(length=64), nullable=True),
    sa.Column('profile', sa.Text(), nullable=True),
    sa.Column('search_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['search_name'], ['searches.search_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_novels_book_name'), 'novels', ['book_name'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter', sa.String(length=64), nullable=True),
    sa.Column('chapter_url', sa.String(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_chapter_url'), 'chapters', ['chapter_url'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    op.drop_index(op.f('ix_chapters_chapter_url'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_novels_book_name'), table_name='novels')
    op.drop_table('novels')
    op.drop_index(op.f('ix_searches_search_name'), table_name='searches')
    op.drop_table('searches')
    # ### end Alembic commands ###
