"""empty message

Revision ID: 62881a76a9c5
Revises: 
Create Date: 2018-09-30 11:01:59.583773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62881a76a9c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('novels', sa.Column('book_shelf', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('novels', 'book_shelf')
    # ### end Alembic commands ###
